import { CardType } from "@/types/CardType"

export function createCard(data: any, currentBinder: any) {
    const card: CardType = {
                    id: 'N/A',
                    card_name: data.name,
                    flavor_name: data.flavor_name,
                    image_uris: data.image_uris || data.card_faces[0].image_uris,
                    add_date: new Date,
                    last_price_update: new Date,
                    binder: currentBinder,
                    condition: "NM",
                    scryfallId: data.id,
                    tcgplayerId: data.tcgplayer_id,
                    tcgplayerEtchedId: data.tcgplayer_etched_id,
                    cardMarketId: data.card_market_id,
                    lang: data.lang,
                    layout: data.layout,
                    uri: data.uri,
                    scryfallUri: data.scryfall_uri,
                    prints_search_uri: data.prints_search_uri,
                    collector_number: data.collector_number,
                    all_parts: data.all_parts ? data.all_parts.map((part: any) => ({
                        name: part.name,
                    })) : [],
                    card_faces: data.card_faces ? data.card_faces.map((face: any) => ({
                        name: face.name,
                        image_uris: face.image_uris
                    })) : [],
                    cmc: data.cmc,
                    color_identity: data.color_identity,
                    color_indicator: data.color_indicator,
                    colors: data.colors,
                    defense: data.defense,
                    edhrank: data.edhrec_rank,
                    game_changer: data.game_changer,
                    keywords: data.keywords,
                    legality: data.legalities,
                    loyalty: data.loyalty,
                    mana_cost: data.mana_cost,
                    oracle_text: data.oracle_text,
                    power: data.power,
                    produced_mana: data.produced_mana,
                    reserved: data.reserved,
                    toughness: data.toughness,
                    type_line: data.type_line,
                    artist: data.artist,
                    frame: data.frame,
                    frame_effects: data.frame_effects,
                    full_art: data.full_art,
                    oversized: data.oversized,
                    prices: data.prices,
                    promo: data.promo,
                    rarity: data.rarity,
                    reprint: data.reprint,
                    scryfall_set: data.set,
                    set_name: data.set_name,
                    set: data.set,
                    variation: data.variation,
                    variation_of: data.variation_of,
                    finishes: data.finishes,
                    foil: false,
                    quantity: 1,
                    set_uri: data.set_uri,
                    buy_price: "0.00",
                    notes: "",
                    favourite: false,
                }
    return card;
}